name:                unliftio
version:             0.2.8.1
synopsis:            The MonadUnliftIO typeclass for unlifting monads to IO (batteries included)
description:         Please see the documentation and README at <https://www.stackage.org/package/unliftio>
homepage:            https://github.com/fpco/unliftio/tree/master/unliftio#readme
license:             MIT
author:              Michael Snoyman, Francesco Mazzoli
maintainer:          michael@snoyman.com
copyright:           2017 FP Complete
category:            Control
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - async > 2.1.1
  - deepseq
  - directory
  - filepath
  - process >= 1.2.0.0
  - stm >= 2.4.3
  - time
  - transformers
  - unliftio-core >= 0.1.1.0

when:
- condition: "!os(Windows)"
  dependencies:
  - unix

library:
  source-dirs:
  - src

  when:
  - condition: os(darwin)
    then:
      c-sources: cbits/time-osx.c
    else:
      when:
      - condition: os(windows)
        then:
          c-sources: cbits/time-windows.c
        else:
          c-sources: cbits/time-posix.c

tests:
  unliftio-spec:
    source-dirs:
    - test
    main: Spec.hs
    dependencies:
    - hspec
    - unliftio
    - QuickCheck
